# Generated by Django 4.2.19 on 2025-02-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_coursecatalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecatalog",
            name="course_number",
            field=models.CharField(max_length=255),
        ),
    ]
