# Generated by Django 5.1.3 on 2025-02-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_coursecatalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseInfoEXT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("course_number", models.IntegerField()),
                ("instructor", models.CharField(max_length=255)),
                ("f_credits", models.IntegerField()),
                ("major_minor", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("total_enrollment", models.IntegerField()),
                ("demand", models.IntegerField()),
            ],
        ),
    ]
