# Generated by Django 4.2.19 on 2025-04-02 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_courseinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseInfo",
        ),
    ]
