# Generated by Django 5.1.3 on 2025-04-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_courseinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseinfo",
            name="instructor",
            field=models.CharField(
                blank=True, default="N/A", max_length=255, null=True
            ),
        ),
    ]
