# Generated by Django 4.2.19 on 2025-04-03 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_courseinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="CourseCatalog",
        ),
        migrations.DeleteModel(
            name="CourseInfo",
        ),
        migrations.DeleteModel(
            name="CourseInfoEXT",
        ),
    ]
