# Generated by Django 4.2.19 on 2025-04-03 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseCatalog",
        ),
        migrations.DeleteModel(
            name="CourseInfo",
        ),
    ]
