# Generated by Django 4.2.19 on 2025-04-02 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_alter_courseinfo_instructor"),
        ("courses", "0010_courseinfo"),
    ]

    operations = []
