# Generated by Django 4.2.19 on 2025-04-03 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_merge_20250402_2213"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="CourseCatalog",
        ),
        migrations.DeleteModel(
            name="CourseInfo",
        ),
        migrations.DeleteModel(
            name="CourseInfoEXT",
        ),
    ]
