# Generated by Django 4.2.19 on 2025-04-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "courses",
            "0012_delete_course_delete_coursecatalog_delete_courseinfo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("course_number", models.CharField(max_length=255)),
                ("course_title", models.CharField(max_length=255)),
                ("prereqs", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CourseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("course_number", models.IntegerField()),
                ("course_title", models.CharField(max_length=255)),
                ("f_credits", models.CharField(max_length=255)),
                ("meeting_pattern", models.CharField(max_length=255)),
                ("meeting_time", models.CharField(max_length=255)),
                ("instructor", models.CharField(max_length=255)),
                ("max_enrollment", models.IntegerField()),
                ("students_enrolled", models.IntegerField()),
                ("primary_requests", models.IntegerField()),
                ("major_requests", models.IntegerField()),
                ("senior_requests", models.IntegerField()),
                ("seniors_enrolled", models.IntegerField()),
                ("junior_requests", models.IntegerField()),
                ("juniors_enrolled", models.IntegerField()),
                ("sophomore_requests", models.IntegerField()),
                ("sophomores_enrolled", models.IntegerField()),
                ("first_year_requests", models.IntegerField()),
                ("first_years_enrolled", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CourseInfoEXT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("course_number", models.IntegerField()),
                ("instructor", models.CharField(max_length=255)),
                ("f_credits", models.IntegerField()),
                ("major_minor", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("total_enrollment", models.IntegerField()),
                ("demand", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "courses_courseinfoext",
            },
        ),
    ]
