# Generated by Django 4.2.19 on 2025-04-03 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="CourseCatalog",
        ),
        migrations.DeleteModel(
            name="CourseInfoEXT",
        ),
    ]
