# Generated by Django 4.2.19 on 2025-04-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_delete_course_delete_coursecatalog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("course_number", models.CharField(max_length=255)),
                ("course_title", models.CharField(max_length=255)),
                ("prereqs", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CourseInfoEXT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("course_number", models.IntegerField()),
                ("instructor", models.CharField(max_length=255)),
                ("f_credits", models.IntegerField()),
                ("major_minor", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("total_enrollment", models.IntegerField()),
                ("demand", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "courses_courseinfoext",
            },
        ),
    ]
