# Generated by Django 4.2.19 on 2025-04-03 02:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_course_coursecatalog_courseinfoext"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseCatalog",
        ),
    ]
