# Generated by Django 4.2.19 on 2025-04-03 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_initial"),
        ("courses", "0017_coursecatalog"),
    ]

    operations = []
