# Generated by Django 4.2.19 on 2025-04-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0018_merge_0012_initial_0017_coursecatalog"),
    ]

    operations = [

    ]
