# Generated by Django 4.2.19 on 2025-04-15 00:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0020_delete_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecatalog",
            name="prereqs",
        ),
    ]
