# Generated by Django 4.2.19 on 2025-04-15 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0021_remove_coursecatalog_prereqs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseCatalog",
        ),
    ]
