# Generated by Django 4.2.19 on 2025-04-15 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0023_coursecatalog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseInfo",
        ),
    ]
